name: WhisperBoard

settings:
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: ""
  SWIFT_VERSION: "5.9"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: 0.1.0

targets:

  # ─── Main App ─────────────────────────────────────────
  WhisperBoard:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: WhisperBoard/Sources/App
      - path: WhisperBoard/Sources/Views
      - path: WhisperBoard/Sources/Shared
      - path: WhisperBoard/Sources/WhisperKit
      - path: WhisperBoard/Resources
        excludes:
          - "Info.plist"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.fmachta.whisperboard
      CODE_SIGN_ENTITLEMENTS: WhisperBoard/Resources/WhisperBoard.entitlements
      INFOPLIST_FILE: WhisperBoard/Resources/Info.plist
    dependencies:
      - target: WhisperBoardKeyboard
      - package: WhisperKit
    scheme:
      testTargets:
        - WhisperBoardTests

  # ─── Keyboard Extension ──────────────────────────────
  # IMPORTANT: No WhisperKit dependency – keeps memory under ~25 MB.
  # The extension captures audio and communicates with the main app
  # via App Group + Darwin notifications.
  WhisperBoardKeyboard:
    type: app-extension
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: WhisperBoard/Sources/KeyboardExtension
        excludes:
          - "*.bak"
          - "WhisperKitIntegration.swift"
      - path: WhisperBoard/Sources/Shared
      - path: WhisperBoard/Sources/WhisperKit/AudioProcessor.swift
      - path: WhisperBoard/KeyboardExtension/Resources
        excludes:
          - "KeyboardInfo.plist"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.fmachta.whisperboard.keyboard
      CODE_SIGN_ENTITLEMENTS: WhisperBoard/KeyboardExtension/Resources/KeyboardExtension.entitlements
      INFOPLIST_FILE: WhisperBoard/KeyboardExtension/Resources/KeyboardInfo.plist
    # No package dependencies – pure UIKit + AVFoundation + system frameworks only

  # ─── Tests ────────────────────────────────────────────
  WhisperBoardTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: WhisperBoardTests
    dependencies:
      - target: WhisperBoard
